"use client";

import type { ReportData } from "@/types/reports";

type ExportPdfProps = {
  data: ReportData;
};

export function ExportPdf({ data }: ExportPdfProps) {
  const handlePrint = () => {
    const html = buildReportHtml(data);
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  };

  return (
    <button
      type="button"
      onClick={handlePrint}
      className="rounded-lg border border-border bg-background px-4 py-2 text-sm font-medium text-foreground hover:bg-muted transition"
    >
      Export PDF
    </button>
  );
}

function buildReportHtml(data: ReportData): string {
  const title = `${data.period.charAt(0).toUpperCase() + data.period.slice(1)} Report`;
  const rows = data.chart.map((p) => `
    <tr>
      <td style="padding:6px 12px;border:1px solid #ddd">${p.label}</td>
      <td style="padding:6px 12px;border:1px solid #ddd;text-align:right">৳${p.revenue.toLocaleString("en-BD")}</td>
      <td style="padding:6px 12px;border:1px solid #ddd;text-align:right">৳${p.profit.toLocaleString("en-BD")}</td>
      <td style="padding:6px 12px;border:1px solid #ddd;text-align:right">${p.orders}</td>
    </tr>
  `).join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${title}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; color: #222; }
  h1 { margin-bottom: 4px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #f5f5f5; padding: 8px 12px; border: 1px solid #ddd; text-align: left; }
  td { padding: 6px 12px; border: 1px solid #ddd; }
  .footer { margin-top: 24px; font-size: 12px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">${data.dateRange.from} — ${data.dateRange.to}</p>
  <table>
    <thead><tr><th>Period</th><th>Revenue</th><th>Profit</th><th>Orders</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by SocialShopBD</div>
</body>
</html>`;
}
